// page.js를 감싸는 파일
// 페이지 바깥에 넣을 내용 작성. ex) <head>, 상단바 등

import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link"
import Image from "next/image"
import logo from "/public/logo/반짝두리.png"
import KNUlogo from "/public/logo/강원대학교2.png"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '두리날씨알리미',
  description: 'Generated by create next app',
  Image: {logo}
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/">
            <div className='main-logo'><Image src={logo} alt="반짝두리" width={150} height={150} /></div>
            <div className='main-title'>두리날씨알리미</div>
          </Link>
        </div>
        {children}

        <footer>
          <div className='footer'>
          <Image src={KNUlogo} alt="강원대학교" width={200} height={83} />
            <p>ⓒ Created by 강원대학교 정유한 유하연 조수현</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
